Add zh_CN and nl languages

diff --git a/package/translate/merge b/package/translate/merge
--- a/package/translate/merge
+++ b/package/translate/merge
@@ -6,9 +6,9 @@
 # https://invent.kde.org/sysadmin/l10n-scripty/-/blob/master/extract-messages.sh
 
 DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`
-plasmoidName=`python3 jsonparse.py $DIR/../metadata.json KPlugin.Name`
+plasmoidName=`python3 jsonParse.py $DIR/../metadata.json KPlugin.Name`
 widgetName="${plasmoidName##*.}" # Strip namespace
-website=`python3 jsonparse.py $DIR/../metadata.json KPlugin.Website`
+website=`python3 jsonParse.py $DIR/../metadata.json KPlugin.Website`
 bugAddress="$website"
 packageRoot=".." # Root of translatable sources
 projectName="plasma_applet_${plasmoidName}" # project name
@@ -34,19 +34,20 @@ potArgs="--from-code=UTF-8 --width=200 --add-location=file"
 # so we need to specify Name, GenericName, Comment, and Keywords.
 # https://github.com/Zren/plasma-applet-lib/issues/1
 # https://savannah.gnu.org/support/?108887
-find "${packageRoot}" -name '*.desktop' | sort > "${DIR}/infiles.list"
-xgettext \
-	${potArgs} \
-	--files-from="${DIR}/infiles.list" \
-	--language=Desktop \
-	-k -kName -kGenericName -kComment -kKeywords \
-	-D "${packageRoot}" \
-	-D "${DIR}" \
-	-o "template.pot.new" \
-	|| \
-	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
 
-sed -i 's/"Content-Type: text\/plain; charset=CHARSET\\n"/"Content-Type: text\/plain; charset=UTF-8\\n"/' "template.pot.new"
+# find "${packageRoot}" -name '*.desktop' | sort > "${DIR}/infiles.list"
+# xgettext \
+# 	${potArgs} \
+# 	--files-from="${DIR}/infiles.list" \
+# 	--language=Desktop \
+# 	-k -kName -kGenericName -kComment -kKeywords \
+# 	-D "${packageRoot}" \
+# 	-D "${DIR}" \
+# 	-o "template.pot.new" \
+# 	|| \
+# 	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
+
+# sed -i 's/"Content-Type: text\/plain; charset=CHARSET\\n"/"Content-Type: text\/plain; charset=UTF-8\\n"/' "template.pot.new"
 
 # See Ki18n's extract-messages.sh for a full example:
 # https://invent.kde.org/sysadmin/l10n-scripty/-/blob/master/extract-messages.sh#L25
@@ -73,7 +74,6 @@ xgettext \
 	--msgid-bugs-address="${bugAddress}" \
 	-D "${packageRoot}" \
 	-D "${DIR}" \
-	--join-existing \
 	-o "template.pot.new" \
 	|| \
 	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
@@ -170,60 +170,60 @@ done
 echo "[merge] Done merging messages"
 
 #---
-echo "[merge] Updating .desktop file"
+# echo "[merge] Updating .desktop file"
 
-# Generate LINGUAS for msgfmt
-if [ -f "$DIR/LINGUAS" ]; then
-	rm "$DIR/LINGUAS"
-fi
-touch "$DIR/LINGUAS"
-for cat in $catalogs; do
-	catLocale=`basename ${cat%.*}`
-	echo "${catLocale}" >> "$DIR/LINGUAS"
-done
+# # Generate LINGUAS for msgfmt
+# if [ -f "$DIR/LINGUAS" ]; then
+# 	rm "$DIR/LINGUAS"
+# fi
+# touch "$DIR/LINGUAS"
+# for cat in $catalogs; do
+# 	catLocale=`basename ${cat%.*}`
+# 	echo "${catLocale}" >> "$DIR/LINGUAS"
+# done
 
-cp -f "$DIR/../metadata.desktop" "$DIR/template.desktop"
-sed -i '/^Name\[/ d; /^GenericName\[/ d; /^Comment\[/ d; /^Keywords\[/ d' "$DIR/template.desktop"
+# cp -f "$DIR/../metadata.desktop" "$DIR/template.desktop"
+# sed -i '/^Name\[/ d; /^GenericName\[/ d; /^Comment\[/ d; /^Keywords\[/ d' "$DIR/template.desktop"
 
-msgfmt \
-	--desktop \
-	--template="$DIR/template.desktop" \
-	-d "$DIR/" \
-	-o "$DIR/new.desktop"
+# msgfmt \
+# 	--desktop \
+# 	--template="$DIR/template.desktop" \
+# 	-d "$DIR/" \
+# 	-o "$DIR/new.desktop"
 
-# Delete empty msgid messages that used the po header
-if [ ! -z "$(grep '^Name=$' "$DIR/new.desktop")" ]; then
-	echo "[merge] Name in metadata.desktop is empty!"
-	sed -i '/^Name\[/ d' "$DIR/new.desktop"
-fi
-if [ ! -z "$(grep '^GenericName=$' "$DIR/new.desktop")" ]; then
-	echo "[merge] GenericName in metadata.desktop is empty!"
-	sed -i '/^GenericName\[/ d' "$DIR/new.desktop"
-fi
-if [ ! -z "$(grep '^Comment=$' "$DIR/new.desktop")" ]; then
-	echo "[merge] Comment in metadata.desktop is empty!"
-	sed -i '/^Comment\[/ d' "$DIR/new.desktop"
-fi
-if [ ! -z "$(grep '^Keywords=$' "$DIR/new.desktop")" ]; then
-	echo "[merge] Keywords in metadata.desktop is empty!"
-	sed -i '/^Keywords\[/ d' "$DIR/new.desktop"
-fi
+# # Delete empty msgid messages that used the po header
+# if [ ! -z "$(grep '^Name=$' "$DIR/new.desktop")" ]; then
+# 	echo "[merge] Name in metadata.desktop is empty!"
+# 	sed -i '/^Name\[/ d' "$DIR/new.desktop"
+# fi
+# if [ ! -z "$(grep '^GenericName=$' "$DIR/new.desktop")" ]; then
+# 	echo "[merge] GenericName in metadata.desktop is empty!"
+# 	sed -i '/^GenericName\[/ d' "$DIR/new.desktop"
+# fi
+# if [ ! -z "$(grep '^Comment=$' "$DIR/new.desktop")" ]; then
+# 	echo "[merge] Comment in metadata.desktop is empty!"
+# 	sed -i '/^Comment\[/ d' "$DIR/new.desktop"
+# fi
+# if [ ! -z "$(grep '^Keywords=$' "$DIR/new.desktop")" ]; then
+# 	echo "[merge] Keywords in metadata.desktop is empty!"
+# 	sed -i '/^Keywords\[/ d' "$DIR/new.desktop"
+# fi
 
-# Place translations at the bottom of the desktop file.
-translatedLines=`cat "$DIR/new.desktop" | grep "]="`
-if [ ! -z "${translatedLines}" ]; then
-	sed -i '/^Name\[/ d; /^GenericName\[/ d; /^Comment\[/ d; /^Keywords\[/ d' "$DIR/new.desktop"
-	if [ "$(tail -c 2 "$DIR/new.desktop" | wc -l)" != "2" ]; then
-		# Does not end with 2 empty lines, so add an empty line.
-		echo "" >> "$DIR/new.desktop"
-	fi
-	echo "${translatedLines}" >> "$DIR/new.desktop"
-fi
+# # Place translations at the bottom of the desktop file.
+# translatedLines=`cat "$DIR/new.desktop" | grep "]="`
+# if [ ! -z "${translatedLines}" ]; then
+# 	sed -i '/^Name\[/ d; /^GenericName\[/ d; /^Comment\[/ d; /^Keywords\[/ d' "$DIR/new.desktop"
+# 	if [ "$(tail -c 2 "$DIR/new.desktop" | wc -l)" != "2" ]; then
+# 		# Does not end with 2 empty lines, so add an empty line.
+# 		echo "" >> "$DIR/new.desktop"
+# 	fi
+# 	echo "${translatedLines}" >> "$DIR/new.desktop"
+# fi
 
-# Cleanup
-mv "$DIR/new.desktop" "$DIR/../metadata.desktop"
-rm "$DIR/template.desktop"
-rm "$DIR/LINGUAS"
+# # Cleanup
+# mv "$DIR/new.desktop" "$DIR/../metadata.desktop"
+# rm "$DIR/template.desktop"
+# rm "$DIR/LINGUAS"
 
 #---
 # Populate ReadMe.md
